export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_ON_CLOSE = 'LOGOUT_ON_CLOSE';
export const CARGANDO = 'CARGANDO';
export const MENSAJE_FLASH = 'MENSAJE_FLASH';
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const POLL_START = 'POLL_START';
export const POLL_STOP = 'POLL_STOP';
export const POLL_PRODUCTOS_START = 'POLL_PRODUCTOS_START';

export const VERIFICAR_ACTUALIZACION_ASYNC = 'VERIFICAR_ACTUALIZACION_ASYNC';
export const SET_ACTUALIZACION_DISPONIBLE = 'SET_ACTUALIZACION_DISPONIBLE';
export const MENSAJE_SUCCESS = 'MENSAJE_SUCCESS';
export const API_ERROR = 'API_ERROR';
export const SET_SESSION = 'SET_SESSION';
export const OBTENER_CONFIGURACION = 'OBTENER_CONFIGURACION';
export const SET_CONFIGURACION = 'SET_CONFIGURACION';
export const SET_SINCRONIZACIONES = 'SET_SINCRONIZACIONES';
export const OBTENER_ULTIMA_SESION = 'OBTENER_ULTIMA_SESION';
export const OBTENER_ALMACENES = 'OBTENER_ALMACENES';
export const OBTENER_SINCRONIZACIONES = 'OBTENER_SINCRONIZACIONES';
export const SET_ALMACENES = 'SET_ALMACENES';
export const GUARDAR_CONFIGURACION_ASYNC = 'GUARDAR_CONFIGURACION_ASYNC';
export const CONFIGURACION_ACTUALIZADA = 'CONFIGURACION_ACTUALIZADA';
export const SET_STATUS_ACTUALIZACION = 'SET_STATUS_ACTUALIZACION';
export const VER_VENTA = 'VER_VENTA';
export const VER_RECEPCION_PAGO = 'VER_RECEPCION_PAGO';
export const SET_AUTORIZACIONES = 'SET_AUTORIZACIONES';

/* impresoras */
export const OBTENER_IMPRESORAS = 'OBTENER_IMPRESORAS';

/* sincronizaciones */
export const CANCELAR_SINCRONIZACION = 'CANCELAR_SINCRONIZACION';
export const SINCRONIZAR_ALMACENES = 'SINCRONIZAR_ALMACENES';
export const SINCRONIZAR_CLIENTES = 'SINCRONIZAR_CLIENTES';
export const SINCRONIZAR_PRODUCTOS = 'SINCRONIZAR_PRODUCTOS';
export const SINCRONIZAR_VENTAS = 'SINCRONIZAR_VENTAS';
export const SINCRONIZAR_RETIROS = 'SINCRONIZAR_RETIROS';
export const SINCRONIZAR_RECEPCIONES_PAGO = 'SINCRONIZAR_RECEPCIONES_PAGO';
export const SINC_SET_HABILITADO = 'SINC_SET_HABILITADO';



/* Autocompletes */
export const AUTOCOMPLETE_PRODUCTO = 'AUTOCOMPLETE_PRODUCTO';
export const AUTOCOMPLETE_CLIENTE = 'AUTOCOMPLETE_CLIENTE';

export const PV_AUTOCOMPLETE_PRODUCTO = 'PV_AUTOCOMPLETE_PRODUCTO';
export const SET_PV_AUTOCOMPLETE_PRODUCTO = 'SET_PV_AUTOCOMPLETE_PRODUCTO';
export const PV_AUTOCOMPLETE_CLIENTE = 'PV_AUTOCOMPLETE_CLIENTE';
export const SET_PV_AUTOCOMPLETE_CLIENTE = 'SET_PV_AUTOCOMPLETE_CLIENTE';

export const PEDIDOS_AUTOCOMPLETE_PRODUCTO = 'PEDIDOS_AUTOCOMPLETE_PRODUCTO';
export const SET_PEDIDOS_AUTOCOMPLETE_PRODUCTO = 'SET_PEDIDOS_AUTOCOMPLETE_PRODUCTO';
export const PEDIDOS_AUTOCOMPLETE_CLIENTE = 'PEDIDOS_AUTOCOMPLETE_CLIENTE';
export const SET_PEDIDOS_AUTOCOMPLETE_CLIENTE = 'SET_PEDIDOS_AUTOCOMPLETE_CLIENTE';

/* Acciones punto de venta */
export const PV_CHANGE_TIPO_PAGO = 'PV_CHANGE_TIPO_PAGO';
export const PV_SELECCIONAR_PINPAD = 'PV_SELECCIONAR_PINPAD';
export const PV_SET_COBROS_PINPAD = 'PV_SET_COBROS_PINPAD';
export const PV_SET_VENTA_ESPERA = 'PV_SET_VENTA_ESPERA';
export const PV_CARGAR_VENTA_ESPERA = 'PV_CARGAR_VENTA_ESPERA';
export const PV_ELIMINAR_VENTA_ESPERA = 'PV_ELIMINAR_VENTA_ESPERA';
export const PV_SET_CLIENTE_AC = 'PV_SET_CLIENTE_AC';
export const PV_BORRAR_DATOS = 'PV_BORRAR_DATOS';
export const PV_RETIRAR_EFECTIVO = 'PV_RETIRAR_EFECTIVO';
export const PV_CHANGE_INFO_EXTRA = 'PV_CHANGE_INFO_EXTRA';
export const PV_ACTUALIZAR_PRODUCTO_INLINE = 'PV_ACTUALIZAR_PRODUCTO_INLINE';
export const PV_GUARDAR_SESION_CAJA = 'PV_GUARDAR_SESION_CAJA';
export const PV_GUARDAR_VENTA = 'PV_GUARDAR_VENTA';
export const PV_NUEVA_VENTA = 'PV_NUEVA_VENTA';
export const PV_ABRIR_CAJA = 'PV_ABRIR_CAJA';
export const PV_CERRAR_CAJA = 'PV_CERRAR_CAJA';
export const PV_LIMPIAR_SESION_CAJA = 'PV_LIMPIAR_SESION_CAJA';
export const PV_SELECCIONAR_USO_CFDI = 'PV_SELECCIONAR_USO_CFDI';
export const PV_SELECCIONAR_PRODUCTO = 'PV_SELECCIONAR_PRODUCTO';
export const PV_SELECCIONAR_CLIENTE = 'PV_SELECCIONAR_CLIENTE';
export const PV_SELECCIONAR_ALMACEN = 'PV_SELECCIONAR_ALMACEN';
export const PV_REQUERIR_FACTURA = 'PV_REQUERIR_FACTURA';
export const PV_ENTREGAR_DOMICILIO = 'PV_ENTREGAR_DOMICILIO';
export const PV_SELECCIONAR_DIRECCION_ENTREGA = 'PV_SELECCIONAR_DIRECCION_ENTREGA';
export const PV_METODO_PAGO = 'PV_METODO_PAGO';
export const PV_SELECCIONAR_METODO_PAGO = 'PV_SELECCIONAR_METODO_PAGO';
export const PV_ELIMINAR_PRODUCTO = 'PV_ELIMINAR_PRODUCTO';
export const PV_IMPRIMIR_RECIBO = 'PV_IMPRIMIR_RECIBO';
export const PV_SET_UM_PRODUCTO = 'PV_SET_UM_PRODUCTO';
export const PV_SIGUIENTE_FOLIO = 'PV_SIGUIENTE_FOLIO';
export const PV_SET_GUARDANDO_VENTA = 'PV_SET_GUARDANDO_VENTA';
export const PV_TOGGLE_OTRA_TERMINAL_PROSEPAGO = 'PV_TOGGLE_OTRA_TERMINAL_PROSEPAGO';
export const PV_SET_PROP = 'PV_SET_PROP';
export const PV_CONCLUIR_VENTA = 'PV_CONCLUIR_VENTA';


/* Acciones pedidos */
export const PEDIDOS_SET_CLIENTE_AC = 'PEDIDOS_SET_CLIENTE_AC';
export const PEDIDOS_EDITAR_PEDIDO = 'PEDIDOS_EDITAR_PEDIDO';
export const PEDIDOS_SET_PEDIDO = 'PEDIDOS_SET_PEDIDO';
export const PEDIDOS_CHANGE_INFO_EXTRA = 'PEDIDOS_CHANGE_INFO_EXTRA';
export const PEDIDOS_ACTUALIZAR_PRODUCTO_INLINE = 'PEDIDOS_ACTUALIZAR_PRODUCTO_INLINE';
export const PEDIDOS_GUARDAR_PEDIDO = 'PEDIDOS_GUARDAR_PEDIDO';
export const PEDIDOS_SELECCIONAR_USO_CFDI = 'PEDIDOS_SELECCIONAR_USO_CFDI';
export const PEDIDOS_SELECCIONAR_PRODUCTO = 'PEDIDOS_SELECCIONAR_PRODUCTO';
export const PEDIDOS_SELECCIONAR_CLIENTE = 'PEDIDOS_SELECCIONAR_CLIENTE';
export const PEDIDOS_SELECCIONAR_ALMACEN = 'PEDIDOS_SELECCIONAR_ALMACEN';
export const PEDIDOS_ENTREGAR_DOMICILIO = 'PEDIDOS_ENTREGAR_DOMICILIO';
export const PEDIDOS_SELECCIONAR_DIRECCION_ENTREGA = 'PEDIDOS_SELECCIONAR_DIRECCION_ENTREGA';
export const PEDIDOS_ELIMINAR_PRODUCTO = 'PEDIDOS_ELIMINAR_PRODUCTO';
export const PEDIDOS_NUEVO_PEDIDO = 'PEDIDOS_NUEVO_PEDIDO';
export const PEDIDOS_SET_UM_PRODUCTO = 'PEDIDOS_SET_UM_PRODUCTO';

/* Acciones recepción de pago */
/* RPF = Recepcion Pago Form */
export const RPF_SET_CLIENTE_AC = 'RPF_SET_CLIENTE_AC';
export const RPF_SELECCIONAR_CLIENTE = 'RPF_SELECCIONAR_CLIENTE';
export const RPF_SELECCIONAR_FACTURA = 'RPF_SELECCIONAR_FACTURA';
export const RPF_SET_AUTOCOMPLETE_CLIENTES = 'RPF_SET_AUTOCOMPLETE_CLIENTES';
export const RPF_SELECCIONAR_ALMACEN = 'RPF_SELECCIONAR_ALMACEN';
export const RPF_GUARDAR_PEDIDO = 'RPF_GUARDAR_PEDIDO';
export const RPF_SET_DATOS_FORM = 'RPF_SET_DATOS_FORM';
export const RPF_SET_CUENTA = 'RPF_SET_CUENTA';
export const RPF_TOGGLE_ENVIAR_CORREO = 'RPF_TOGGLE_ENVIAR_CORREO';
export const RPF_SET_ALMACEN = 'RPF_SET_ALMACEN';
export const RPF_SET_CAJERO = 'RPF_SET_CAJERO';
export const RPF_SET_FECHA = 'RPF_SET_FECHA';
export const RPF_SET_TIPO_ABONO = 'RPF_SET_TIPO_ABONO';
export const RPF_SET_TIPO_PAGO = 'RPF_SET_TIPO_PAGO';
export const RPF_SET_ABONO = 'RPF_SET_ABONO';
export const RPF_SET_IMPORTE = 'RPF_SET_IMPORTE';
export const RPF_SET_MONEDA = 'RPF_SET_MONEDA';
export const RPF_SET_NO_CHEQUE = 'RPF_SET_NO_CHEQUE';
export const RPF_SET_BANCO = 'RPF_SET_BANCO';
export const RPF_SET_COMENTARIOS = 'RPF_SET_COMENTARIOS';
export const RPF_SET_ATTR = 'RPF_SET_ATTR';
export const RPF_GUARDAR = 'RPF_GUARDAR';
export const RPF_LIMPIAR_FORM = 'RPF_LIMPIAR_FORM';

/* Acciones verificador de precios */
export const VP_AUTOCOMPLETE_PRODUCTO = 'VP_AUTOCOMPLETE_PRODUCTO';
export const SET_VP_AUTOCOMPLETE_PRODUCTO = 'SET_VP_AUTOCOMPLETE_PRODUCTO';
