export default {
  PUNTO_VENTA: {
    INGRESAR_PAGO_EFECTIVO: 'f1',
    INGRESAR_PAGO_CHEQUE: 'f2',
    INGRESAR_PAGO_TARJETA: 'f3',
    INGRESAR_PAGO_TRANSFERENCIA: 'f4',
    INGRESAR_PAGO_FONDO: 'f5',
    GUARDAR_VENTA: 'f12',
    FOCUS_INPUT_CLIENTE: 'f10',
    FOCUS_INPUT_PRODUCTO: 'p',
    BLUR: 'escape',
    VERIFICADOR_PRECIOS: 'f9',
    MOSTRAR_ATAJOS: 'h',
  },
}